<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $comps = Data::get('components') ?>


<!-- container -->
<div class="container">

    <?php Layout::setSubViewContainer('titlecontainer'); ?>

            <p><b>The ArmoredCore (API) has loaded the following components:</b></p>
            <table class="table table-striped">
                <thead>
                <tr>
                <th>Component Name</th><th>Runtime Object Class name</th><th>Actions</th>
                </tr>
                </thead>
                <tbody>
            <?php foreach($comps as $key => $value){?>
                <tr>
                    <td scope="row"><?= $key ?></td><td><?= get_class($value)?></td><td><a href="<?=Url::toRoute('devtools/inspect', $key)?>" class="btn btn-info" role="button">Inspect</a></td>
                </tr>
            <?php } ?>
                </tbody>
            </table>

        </article>
        <!-- /Article -->
    </div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>