<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

$serverModules = Data::get('serverModules');

Layout::includeLayout('header') ?>


<!-- container -->
<div class="container">

    <?php Layout::setSubViewContainer('titlecontainer'); ?>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">

                <div class="panel panel-default">
                    <div class="panel-body">

                        <form method="post" action="<?=Url::toRoute('devtools/ControllerModelSelector')?>">
                            <div class="top-margin">
                                <label>Server Module<small><i> (Please select the Server Module:)</i></small><span class="text-danger">*</span></label>
                                <select class="form-control" name="servermodulename">
                                <?php foreach ($serverModules as $module){ ?>
                                    <option value="<?=$module?>"><?=$module?></option>
                                <?php } ?>
                                </select>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-lg-8">

                                </div>
                                <div class="col-lg-4 text-right">
                                    <button class="btn btn-action" type="submit">Next</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>

        </article>
        <!-- /Article -->

        </div>

</div>

<?php Layout::includeLayout('footer') ?>
