<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $finance = Data::get('finance') ?>
<?php ErrMgr::attach($finance) ?>

	<!-- container -->
	<div class="container">

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Edit Book</h1>
				</header>
					<div class="panel panel-default">
						<div class="panel-body">
                            <hr>

							<form class="form-horizontal" method="post" action="<?=Url::toRoute('finance/update', $finance->id)?>">

                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="name">Descrição:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
                                        <input type="text" value="<?=$finance->descricao?>" class="form-control" required name="descricao" placeholder="Inserir Descrição">
                                        <?= ErrMgr::bind('descricao') ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="name">Valor:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
                                        <input type="text" required value="<?=$finance->valor?>" class="form-control" name="valor" placeholder="Inserir Valor">
                                        <?= ErrMgr::bind('valor') ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="name">Tipo de Categoria:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
                                        <input type="text" required value="<?=$finance->tipocategoria?>" class="form-control" name="valor" placeholder="Inserir Categoria">
                                        <?= ErrMgr::bind('tipocategoria') ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="name">Data:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">

                                    </div>
                                </div>

								<hr>

									<div class="col-lg-4 text-right">
										<button class="btn btn-default" type="submit">Save</button>
									</div>
								</div>
							</form>
						</div>
					</div>

			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>