<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header');
$modelNames = Data::get('modelnames');
$controllerNames = Data::get('controllernames');
$serverModuleName = Data::get('servermodulename');

?>


<!-- container -->
<div class="container">

    <?php Layout::setSubViewContainer('titlecontainer'); ?>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">

                <div class="panel panel-default">
                    <div class="panel-body">

                        <h3 class="thin text-left">Server Module has the following controllers:</h3>

                        <?php foreach ($controllerNames as $controller){ ?>
                            <pre><code class="nohighlight"><?=$controller?></code></pre>
                        <?php } ?>

                        <h3 class="thin text-left">Please provide the following information:</h3>
                        <form method="post" action="<?=Url::toRoute('devtools/ControllerGenerator')?>">
                            <div class="top-margin">
                                <label>Model Class Name <small><i> (Name of the model you want to use.)</i></small><span class="text-danger">*</span></label>
                                <select class="form-control" name="modelname">
                                <?php foreach ($modelNames as $model){ ?>
                                    <option value="<?=$model?>"><?=$model?></option>
                                <?php } ?>
                                </select>
                                <input type="hidden" name="servermodulename" value="<?=$serverModuleName?>">
                            </div>

                            <hr>

                            <div class="row">
                                <div class="col-lg-8">

                                </div>
                                <div class="col-lg-4 text-right">
                                    <button class="btn btn-action" type="submit">Generate</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>

        </article>
        <!-- /Article -->
    </div>

</div>

<?php Layout::includeLayout('footer') ?>